repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=5000']  # Max file size limit in kilobytes

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.9.12  # Use the appropriate Python version

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88']  # Configuring specific Flake8 rules

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.32.0
    hooks:
      - id: eslint
        args: ['--fix']

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.1  # Use the most recent stable version of SQLFluff
    hooks:
      - id: sqlfluff-lint
        args: ['--config', '.sqlfluff']  # Pointing to your SQLFluff config file

      - id: sqlfluff-fix
        args: ['--config', '.sqlfluff']  # Auto-fix SQL issues based on SQLFluff rules

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.0
    hooks:
      - id: nbqa-flake8
        name: flake8 on notebooks
        additional_dependencies: [flake8]
        args:
          - "--ignore=E203,W503"  # flake8-specific options here
        nbqa_args: []
        files: \.ipynb$
        always_run: true

      - id: nbqa-black
        name: black on notebooks
        additional_dependencies: [black]
        args:
          - "--line-length=88"  # black-specific options
        nbqa_args: []
        files: \.ipynb$
        always_run: true

      # - id: nbqa-mypy
      #   name: mypy on notebooks
      #   additional_dependencies: [mypy]
      #   args:
      #     - "."
      #   files: \.ipynb$
      #   always_run: true

      # - id: nbqa-pylint
      #   name: pylint on notebooks
      #   additional_dependencies: [pylint]
      #   args:
      #     - "."
      #     - "--disable=C0114,C0116"
      #   files: \.ipynb$
      #   always_run: true

      # - id: nbqa-pyupgrade
      #   name: pyupgrade on notebooks
      #   additional_dependencies: [pyupgrade]
      #   args:
      #     - "."
      #     - "--py36-plus"
      #   files: \.ipynb$
      #   always_run: true
